# Generated by Django 5.1.6 on 2025-10-04 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dfans_url',
            field=models.URLField(blank=True, default='https://dfans.co/', verbose_name='Dfans URL'),
        ),
    ]
