# Generated by Django 5.1.6 on 2025-11-02 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_dfans_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='global_media_description',
            field=models.TextField(blank=True, help_text='If set, this replaces per-video descriptions', verbose_name='Global media description'),
        ),
    ]
