# Generated by Django 5.1.6 on 2026-05-06 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_global_media_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='adFreeUser',
            field=models.BooleanField(db_index=True, default=False, verbose_name='ad-free user'),
        ),
    ]
