# Generated by Django 5.1.6 on 2026-06-26 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_adfreeuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dfans_url',
            field=models.URLField(blank=True, default='', verbose_name='Dfans URL'),
        ),
    ]
