# Generated by Django 5.1.6 on 2026-08-15 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_referral_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='advertiserUser',
            field=models.BooleanField(db_index=True, default=False, verbose_name='advertiser'),
        ),
        migrations.AlterField(
            model_name='user',
            name='referral_code',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=32, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='referred_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='referred_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
