# Generated by Django 5.1.6 on 2026-08-31 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_advertiseruser_alter_user_referral_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notification_on_new_subscriptions',
            field=models.BooleanField(default=True, help_text='Receive an email when a new subscriber starts a paid creator subscription.', verbose_name='Email me when someone starts a subscription'),
        ),
        migrations.AddField(
            model_name='user',
            name='notification_on_premium_purchases',
            field=models.BooleanField(default=True, help_text='Receive an email for each new premium content sale.', verbose_name='Email me when someone purchases my premium content'),
        ),
        migrations.AddField(
            model_name='user',
            name='notification_on_subscription_renewals',
            field=models.BooleanField(default=False, help_text='Receive an email when an existing paid subscription renews.', verbose_name='Email me when a subscription renews'),
        ),
    ]
