# Generated by Django 5.1.6 on 2026-08-30 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identity_providers', '0004_alter_identityprovidercategorymapping_map_to'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IdentityProviderUserLog',
        ),
    ]
