[uwsgi]

chdir = /home/mediacms.io/mediacms/
virtualenv = /home/mediacms.io
module = cms.wsgi

uid=www-data
gid=www-data

processes = 16
threads = 1
so-reuseport = true 
listen = 2048
max-requests = 10000
max-requests-delta = 500

master = true
harakiri = 30
harakiri-verbose = true

socket = 127.0.0.1:9000

cheaper = 4 
cheaper-initial = 6 
cheaper-step = 2
cheaper-idle = 120
cheaper-algo = busyness
cheaper-busyness = 50 

vacuum = true

hook-master-start = unix_signal:15 gracefully_kill_them_all
need-app = true
die-on-term = true
buffer-size=32768
