# Generated by Django 5.1.6 on 2026-04-05 20:47

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerSaga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saga_type', models.CharField(db_index=True, max_length=64)),
                ('external_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('compensating', 'Compensating'), ('compensated', 'Compensated')], db_index=True, default='pending', max_length=16)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('metadata_version', models.PositiveSmallIntegerField(default=1)),
                ('started_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('compensated_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_sagas_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('can_manage_ledger_sagas', 'Can manage ledger sagas'), ('can_compensate_ledger_sagas', 'Can compensate ledger sagas'), ('can_view_ledger_sagas', 'Can view ledger sagas')],
            },
        ),
        migrations.CreateModel(
            name='LedgerTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(db_index=True, max_length=32)),
                ('external_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('request_hash', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('memo', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('metadata_version', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('posted', 'Posted'), ('reversed', 'Reversed')], db_index=True, default='posted', max_length=16)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='token_transactions_created', to=settings.AUTH_USER_MODEL)),
                ('reversal_of', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal_txn', to='ledger.ledgertransaction')),
            ],
            options={
                'permissions': [('can_apply_raw_ledger_transaction', 'Can apply raw ledger transactions'), ('can_create_pending_ledger_transaction', 'Can create pending ledger transactions'), ('can_reverse_ledger_transaction', 'Can reverse ledger transactions'), ('can_impersonate_ledger_creator', 'Can set created_by to another user')],
            },
        ),
        migrations.CreateModel(
            name='LedgerSagaStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_key', models.CharField(max_length=64)),
                ('step_order', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('compensated', 'Compensated'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=16)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('metadata_version', models.PositiveSmallIntegerField(default=1)),
                ('started_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('compensated_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('saga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='ledger.ledgersaga')),
                ('compensation_txn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compensated_saga_steps', to='ledger.ledgertransaction')),
                ('txn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='saga_steps', to='ledger.ledgertransaction')),
            ],
            options={
                'permissions': [('can_view_ledger_saga_steps', 'Can view ledger saga steps')],
            },
        ),
        migrations.CreateModel(
            name='LedgerOutbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(db_index=True, max_length=64)),
                ('aggregate_type', models.CharField(db_index=True, default='ledger_transaction', max_length=32)),
                ('aggregate_id', models.BigIntegerField(db_index=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('dispatched', 'Dispatched'), ('failed', 'Failed'), ('dead_lettered', 'Dead lettered')], db_index=True, default='pending', max_length=16)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('metadata_version', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('dispatched_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('fail_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('dead_lettered_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('dead_letter_reason', models.TextField(blank=True, default='')),
                ('last_attempt_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('next_retry_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('redrive_count', models.PositiveIntegerField(default=0)),
                ('last_redriven_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('txn', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outbox_events', to='ledger.ledgertransaction')),
            ],
            options={
                'permissions': [('can_manage_ledger_outbox', 'Can manage ledger outbox')],
            },
        ),
        migrations.CreateModel(
            name='DepositSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('chain', models.CharField(db_index=True, max_length=32)),
                ('asset_code', models.CharField(db_index=True, max_length=32)),
                ('token_contract_address', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('deposit_address', models.CharField(max_length=128, unique=True)),
                ('address_derivation_ref', models.CharField(max_length=128, unique=True)),
                ('status', models.CharField(choices=[('awaiting_payment', 'Awaiting payment'), ('seen_onchain', 'Seen on-chain'), ('confirming', 'Confirming'), ('credited', 'Credited'), ('expired', 'Expired'), ('failed', 'Failed')], db_index=True, default='awaiting_payment', max_length=32)),
                ('min_amount', models.BigIntegerField(default=1)),
                ('required_confirmations', models.PositiveIntegerField(default=1)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('observed_txid', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('observed_amount', models.BigIntegerField(blank=True, null=True)),
                ('confirmations', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('metadata_version', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposit_sessions_created', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deposit_sessions', to=settings.AUTH_USER_MODEL)),
                ('credited_ledger_txn', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credited_deposit_session', to='ledger.ledgertransaction')),
            ],
            options={
                'permissions': [('can_manage_deposit_sessions', 'Can manage deposit sessions'), ('can_view_deposit_sessions', 'Can view deposit sessions'), ('can_credit_confirmed_deposits', 'Can credit confirmed deposits')],
            },
        ),
        migrations.CreateModel(
            name='ObservedOnchainTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(max_length=160, unique=True)),
                ('chain', models.CharField(db_index=True, max_length=32)),
                ('txid', models.CharField(db_index=True, max_length=128)),
                ('log_index', models.BigIntegerField(blank=True, null=True)),
                ('block_number', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('from_address', models.CharField(blank=True, default='', max_length=128)),
                ('to_address', models.CharField(db_index=True, max_length=128)),
                ('token_contract_address', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('asset_code', models.CharField(db_index=True, max_length=32)),
                ('amount', models.BigIntegerField()),
                ('confirmations', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('observed', 'Observed'), ('confirming', 'Confirming'), ('confirmed', 'Confirmed'), ('credited', 'Credited'), ('ignored', 'Ignored'), ('failed', 'Failed')], db_index=True, default='observed', max_length=16)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('metadata_version', models.PositiveSmallIntegerField(default=1)),
                ('first_seen_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('confirmed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credited_ledger_txn', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credited_onchain_transfer', to='ledger.ledgertransaction')),
                ('deposit_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='observed_transfers', to='ledger.depositsession')),
            ],
            options={
                'permissions': [('can_record_onchain_observations', 'Can record on-chain observations'), ('can_view_onchain_transfers', 'Can view on-chain transfers')],
            },
        ),
        migrations.CreateModel(
            name='TokenWallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_type', models.CharField(choices=[('user', 'User'), ('system', 'System')], db_index=True, default='user', max_length=16)),
                ('system_key', models.CharField(blank=True, choices=[('issuance', 'Issuance'), ('platform_fees', 'Platform fees'), ('external_asset_clearing', 'External asset clearing')], max_length=32, null=True, unique=True)),
                ('balance', models.BigIntegerField(default=0)),
                ('allow_negative', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('held_balance', models.BigIntegerField(default=0)),
                ('risk_status', models.CharField(choices=[('clear', 'Clear'), ('review', 'Review'), ('blocked', 'Blocked')], db_index=True, default='clear', max_length=16)),
                ('risk_reason', models.TextField(blank=True, default='')),
                ('review_required', models.BooleanField(db_index=True, default=False)),
                ('daily_outflow_limit', models.BigIntegerField(blank=True, null=True)),
                ('hourly_outflow_limit', models.BigIntegerField(blank=True, null=True)),
                ('daily_inflow_limit', models.BigIntegerField(blank=True, null=True)),
                ('hourly_inflow_limit', models.BigIntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='token_wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LedgerVelocityWindow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('transfer', 'Transfer'), ('purchase', 'Purchase')], db_index=True, max_length=32)),
                ('window_seconds', models.PositiveIntegerField(db_index=True)),
                ('amount', models.BigIntegerField(default=0)),
                ('count', models.PositiveIntegerField(default=0)),
                ('window_start', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='velocity_windows', to='ledger.tokenwallet')),
            ],
            options={
                'permissions': [('can_view_wallet_velocity', 'Can view wallet velocity windows')],
            },
        ),
        migrations.CreateModel(
            name='LedgerHold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField()),
                ('reason', models.CharField(blank=True, default='', max_length=128)),
                ('released', models.BooleanField(db_index=True, default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('metadata_version', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('released_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_holds_created', to=settings.AUTH_USER_MODEL)),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_holds_released', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holds', to='ledger.tokenwallet')),
            ],
            options={
                'permissions': [('can_manage_wallet_holds', 'Can manage wallet holds'), ('can_view_wallet_holds', 'Can view wallet holds')],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.BigIntegerField()),
                ('balance_after', models.BigIntegerField()),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('txn', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='ledger.ledgertransaction')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='ledger.tokenwallet')),
            ],
            options={
                'permissions': [('can_view_ledger_entries', 'Can view ledger entries')],
            },
        ),
        migrations.AddField(
            model_name='depositsession',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deposit_sessions', to='ledger.tokenwallet'),
        ),
        migrations.CreateModel(
            name='WalletRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal')], db_index=True, max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('canceled', 'Canceled'), ('completed', 'Completed')], db_index=True, default='pending', max_length=16)),
                ('amount', models.BigIntegerField()),
                ('asset_code', models.CharField(default='TOKENS', max_length=16)),
                ('destination_address', models.CharField(blank=True, max_length=255)),
                ('reference', models.CharField(db_index=True, max_length=64, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('metadata_version', models.PositiveIntegerField(default=1)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_requests_created', to=settings.AUTH_USER_MODEL)),
                ('hold', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_request', to='ledger.ledgerhold')),
                ('linked_ledger_txn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wallet_requests', to='ledger.ledgertransaction')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_requests_reviewed', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wallet_requests', to='ledger.tokenwallet')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'permissions': [('can_manage_wallet_requests', 'Can manage wallet requests'), ('can_review_wallet_requests', 'Can review wallet requests')],
            },
        ),
        migrations.AddConstraint(
            model_name='ledgertransaction',
            constraint=models.CheckConstraint(condition=models.Q(('external_id__isnull', True), ('request_hash__isnull', False), _connector='OR'), name='ledgertransaction_request_hash_if_external_id'),
        ),
        migrations.AddConstraint(
            model_name='ledgertransaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('reversal_of__isnull', True), ('status', 'pending')), models.Q(('reversal_of__isnull', True), ('status', 'posted')), models.Q(('reversal_of__isnull', False), ('status', 'reversed')), _connector='OR'), name='ledgertransaction_reversal_requires_reversal_of'),
        ),
        migrations.AddIndex(
            model_name='ledgersagastep',
            index=models.Index(fields=['saga', 'step_order'], name='ledger_ledg_saga_id_cf4ff0_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgersagastep',
            index=models.Index(fields=['saga', 'status'], name='ledger_ledg_saga_id_f2bb8f_idx'),
        ),
        migrations.AddConstraint(
            model_name='ledgersagastep',
            constraint=models.UniqueConstraint(fields=('saga', 'step_key'), name='ledgersagastep_unique_step_key_per_saga'),
        ),
        migrations.AddConstraint(
            model_name='ledgersagastep',
            constraint=models.UniqueConstraint(fields=('saga', 'step_order'), name='ledgersagastep_unique_step_order_per_saga'),
        ),
        migrations.AddIndex(
            model_name='ledgeroutbox',
            index=models.Index(fields=['status', 'created_at'], name='ledger_ledg_status_9f7a79_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgeroutbox',
            index=models.Index(fields=['topic', 'status', 'created_at'], name='ledger_ledg_topic_2fcdd1_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgeroutbox',
            index=models.Index(fields=['aggregate_type', 'aggregate_id'], name='ledger_ledg_aggrega_27da68_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgeroutbox',
            index=models.Index(fields=['status', 'next_retry_at'], name='ledger_ledg_status_420e42_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgeroutbox',
            index=models.Index(fields=['status', 'dead_lettered_at'], name='ledger_ledg_status_c1d618_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgeroutbox',
            index=models.Index(fields=['status', 'last_attempt_at'], name='ledger_ledg_status_0ffd5e_idx'),
        ),
        migrations.AddIndex(
            model_name='observedonchaintransfer',
            index=models.Index(fields=['chain', 'txid'], name='ledger_obse_chain_af5967_idx'),
        ),
        migrations.AddIndex(
            model_name='observedonchaintransfer',
            index=models.Index(fields=['chain', 'to_address', 'status'], name='ledger_obse_chain_f7d97d_idx'),
        ),
        migrations.AddIndex(
            model_name='observedonchaintransfer',
            index=models.Index(fields=['deposit_session', 'status'], name='ledger_obse_deposit_8e5bdc_idx'),
        ),
        migrations.AddIndex(
            model_name='observedonchaintransfer',
            index=models.Index(fields=['status', 'first_seen_at'], name='ledger_obse_status_af2474_idx'),
        ),
        migrations.AddConstraint(
            model_name='observedonchaintransfer',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='observedonchaintransfer_amount_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='observedonchaintransfer',
            constraint=models.CheckConstraint(condition=models.Q(('confirmations__gte', 0)), name='observedonchaintransfer_confirmations_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='tokenwallet',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('wallet_type', 'user'), ('user__isnull', False), ('system_key__isnull', True)), models.Q(('wallet_type', 'system'), ('user__isnull', True), ('system_key__isnull', False)), _connector='OR'), name='tokenwallet_valid_owner_shape'),
        ),
        migrations.AddConstraint(
            model_name='tokenwallet',
            constraint=models.CheckConstraint(condition=models.Q(('allow_negative', True), ('balance__gte', 0), _connector='OR'), name='tokenwallet_balance_non_negative_unless_allowed'),
        ),
        migrations.AddConstraint(
            model_name='tokenwallet',
            constraint=models.CheckConstraint(condition=models.Q(('held_balance__gte', 0)), name='tokenwallet_held_balance_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='tokenwallet',
            constraint=models.CheckConstraint(condition=models.Q(('balance__gte', models.F('held_balance')), ('allow_negative', True), _connector='OR'), name='tokenwallet_balance_gte_held_balance_if_not_negative'),
        ),
        migrations.AddIndex(
            model_name='ledgervelocitywindow',
            index=models.Index(fields=['wallet', 'action', 'window_seconds', 'window_start'], name='ledger_ledg_wallet__0ecc4f_idx'),
        ),
        migrations.AddConstraint(
            model_name='ledgervelocitywindow',
            constraint=models.UniqueConstraint(fields=('wallet', 'action', 'window_seconds', 'window_start'), name='ledgervelocitywindow_unique_wallet_action_window'),
        ),
        migrations.AddConstraint(
            model_name='ledgervelocitywindow',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='ledgervelocitywindow_amount_gte_0'),
        ),
        migrations.AddIndex(
            model_name='ledgerhold',
            index=models.Index(fields=['wallet', 'released', 'created_at'], name='ledger_ledg_wallet__2cb95c_idx'),
        ),
        migrations.AddConstraint(
            model_name='ledgerhold',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='ledgerhold_amount_gt_0'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['wallet', '-created_at'], name='ledger_ledg_wallet__45faba_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['txn'], name='ledger_ledg_txn_id_4534fd_idx'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(('delta', 0), _negated=True), name='ledgerentry_delta_non_zero'),
        ),
        migrations.AddIndex(
            model_name='depositsession',
            index=models.Index(fields=['user', 'status', '-created_at'], name='ledger_depo_user_id_fe4e5b_idx'),
        ),
        migrations.AddIndex(
            model_name='depositsession',
            index=models.Index(fields=['wallet', 'status', '-created_at'], name='ledger_depo_wallet__329a64_idx'),
        ),
        migrations.AddIndex(
            model_name='depositsession',
            index=models.Index(fields=['chain', 'asset_code', 'status'], name='ledger_depo_chain_ae4354_idx'),
        ),
        migrations.AddIndex(
            model_name='depositsession',
            index=models.Index(fields=['expires_at', 'status'], name='ledger_depo_expires_a4c510_idx'),
        ),
        migrations.AddConstraint(
            model_name='depositsession',
            constraint=models.CheckConstraint(condition=models.Q(('min_amount__gt', 0)), name='depositsession_min_amount_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='depositsession',
            constraint=models.CheckConstraint(condition=models.Q(('required_confirmations__gte', 1)), name='depositsession_required_confirmations_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='depositsession',
            constraint=models.CheckConstraint(condition=models.Q(('confirmations__gte', 0)), name='depositsession_confirmations_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='depositsession',
            constraint=models.CheckConstraint(condition=models.Q(('observed_amount__isnull', True), ('observed_amount__gt', 0), _connector='OR'), name='depositsession_observed_amount_gt_0_if_present'),
        ),
        migrations.AddIndex(
            model_name='walletrequest',
            index=models.Index(fields=['wallet', 'status', 'created_at'], name='ledger_wall_wallet__ff5fd4_idx'),
        ),
        migrations.AddIndex(
            model_name='walletrequest',
            index=models.Index(fields=['wallet', 'request_type', 'created_at'], name='ledger_wall_wallet__d45216_idx'),
        ),
    ]
