# Generated by Django 5.1.6 on 2026-04-05 22:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain', models.CharField(db_index=True, max_length=32)),
                ('asset_code', models.CharField(db_index=True, max_length=32)),
                ('token_contract_address', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('display_label', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=128, unique=True)),
                ('address_derivation_ref', models.CharField(max_length=128, unique=True)),
                ('required_confirmations', models.PositiveIntegerField(default=1)),
                ('min_amount', models.BigIntegerField(default=1)),
                ('session_ttl_seconds', models.PositiveIntegerField(default=3600)),
                ('status', models.CharField(choices=[('available', 'Available'), ('allocated', 'Allocated'), ('retired', 'Retired')], db_index=True, default='available', max_length=16)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('metadata_version', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allocated_deposit_session', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allocated_address', to='ledger.depositsession')),
            ],
            options={
                'permissions': [('can_manage_deposit_addresses', 'Can manage deposit addresses'), ('can_view_deposit_addresses', 'Can view deposit addresses')],
                'indexes': [models.Index(fields=['status', 'chain', 'asset_code'], name='ledger_depo_status_3d7288_idx'), models.Index(fields=['status', 'chain', 'asset_code', 'token_contract_address'], name='ledger_depo_status_c0615c_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('required_confirmations__gte', 1)), name='depositaddress_required_confirmations_gte_1'), models.CheckConstraint(condition=models.Q(('min_amount__gt', 0)), name='depositaddress_min_amount_gt_0'), models.CheckConstraint(condition=models.Q(('session_ttl_seconds__gt', 0)), name='depositaddress_session_ttl_seconds_gt_0')],
            },
        ),
    ]
