# Generated by Django 5.1.6 on 2026-03-22 18:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_alter_ledgerentry_txn_alter_ledgerentry_wallet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgertransaction',
            name='request_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddConstraint(
            model_name='ledgertransaction',
            constraint=models.CheckConstraint(condition=models.Q(('external_id__isnull', True), ('request_hash__isnull', False), _connector='OR'), name='ledgertransaction_request_hash_if_external_id'),
        ),
    ]
