# Generated by Django 5.1.6 on 2026-03-22 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_ledgertransaction_request_hash_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tokenwallet',
            name='tokenwallet_balance_non_negative',
        ),
        migrations.AddField(
            model_name='tokenwallet',
            name='allow_negative',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tokenwallet',
            name='system_key',
            field=models.CharField(blank=True, choices=[('issuance', 'Issuance'), ('platform_fees', 'Platform fees')], max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tokenwallet',
            name='wallet_type',
            field=models.CharField(choices=[('user', 'User'), ('system', 'System')], db_index=True, default='user', max_length=16),
        ),
        migrations.AlterField(
            model_name='tokenwallet',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='token_wallet', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='tokenwallet',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('wallet_type', 'user'), ('user__isnull', False), ('system_key__isnull', True)), models.Q(('wallet_type', 'system'), ('user__isnull', True), ('system_key__isnull', False)), _connector='OR'), name='tokenwallet_valid_owner_shape'),
        ),
        migrations.AddConstraint(
            model_name='tokenwallet',
            constraint=models.CheckConstraint(condition=models.Q(('allow_negative', True), ('balance__gte', 0), _connector='OR'), name='tokenwallet_balance_non_negative_unless_allowed'),
        ),
    ]
