# Generated by Django 5.1.6 on 2026-03-29 13:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_remove_tokenwallet_tokenwallet_balance_non_negative_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerOutbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(db_index=True, max_length=64)),
                ('aggregate_type', models.CharField(db_index=True, default='ledger_transaction', max_length=32)),
                ('aggregate_id', models.BigIntegerField(db_index=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('dispatched', 'Dispatched'), ('failed', 'Failed'), ('dead_lettered', 'Dead lettered')], db_index=True, default='pending', max_length=16)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('metadata_version', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('dispatched_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('fail_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('dead_lettered_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('dead_letter_reason', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='LedgerSaga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saga_type', models.CharField(db_index=True, max_length=64)),
                ('external_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('compensating', 'Compensating'), ('compensated', 'Compensated')], db_index=True, default='pending', max_length=16)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('metadata_version', models.PositiveSmallIntegerField(default=1)),
                ('started_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('compensated_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='LedgerSagaStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_key', models.CharField(max_length=64)),
                ('step_order', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('compensated', 'Compensated'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=16)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('metadata_version', models.PositiveSmallIntegerField(default=1)),
                ('started_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('compensated_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='ledgertransaction',
            name='metadata_version',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ledgertransaction',
            name='reversal_of',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal_txn', to='ledger.ledgertransaction'),
        ),
        migrations.AddField(
            model_name='ledgertransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('posted', 'Posted'), ('reversed', 'Reversed')], db_index=True, default='posted', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='ledgertransaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('reversal_of__isnull', True), ('status', 'pending')), models.Q(('reversal_of__isnull', True), ('status', 'posted')), models.Q(('reversal_of__isnull', False), ('status', 'reversed')), _connector='OR'), name='ledgertransaction_reversal_requires_reversal_of'),
        ),
        migrations.AddField(
            model_name='ledgeroutbox',
            name='txn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outbox_events', to='ledger.ledgertransaction'),
        ),
        migrations.AddField(
            model_name='ledgersaga',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_sagas_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ledgersagastep',
            name='compensation_txn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compensated_saga_steps', to='ledger.ledgertransaction'),
        ),
        migrations.AddField(
            model_name='ledgersagastep',
            name='saga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='ledger.ledgersaga'),
        ),
        migrations.AddField(
            model_name='ledgersagastep',
            name='txn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='saga_steps', to='ledger.ledgertransaction'),
        ),
        migrations.AddIndex(
            model_name='ledgeroutbox',
            index=models.Index(fields=['status', 'created_at'], name='ledger_ledg_status_9f7a79_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgeroutbox',
            index=models.Index(fields=['topic', 'status', 'created_at'], name='ledger_ledg_topic_2fcdd1_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgeroutbox',
            index=models.Index(fields=['aggregate_type', 'aggregate_id'], name='ledger_ledg_aggrega_27da68_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgersagastep',
            index=models.Index(fields=['saga', 'step_order'], name='ledger_ledg_saga_id_cf4ff0_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgersagastep',
            index=models.Index(fields=['saga', 'status'], name='ledger_ledg_saga_id_f2bb8f_idx'),
        ),
        migrations.AddConstraint(
            model_name='ledgersagastep',
            constraint=models.UniqueConstraint(fields=('saga', 'step_key'), name='ledgersagastep_unique_step_key_per_saga'),
        ),
        migrations.AddConstraint(
            model_name='ledgersagastep',
            constraint=models.UniqueConstraint(fields=('saga', 'step_order'), name='ledgersagastep_unique_step_order_per_saga'),
        ),
    ]
