# Generated by Django 5.1.6 on 2026-03-29 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0005_ledgeroutbox_ledgersaga_ledgersagastep_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ledgerentry',
            options={'permissions': [('can_view_ledger_entries', 'Can view ledger entries')]},
        ),
        migrations.AlterModelOptions(
            name='ledgeroutbox',
            options={'permissions': [('can_manage_ledger_outbox', 'Can manage ledger outbox')]},
        ),
        migrations.AlterModelOptions(
            name='ledgersaga',
            options={'permissions': [('can_manage_ledger_sagas', 'Can manage ledger sagas'), ('can_compensate_ledger_sagas', 'Can compensate ledger sagas'), ('can_view_ledger_sagas', 'Can view ledger sagas')]},
        ),
        migrations.AlterModelOptions(
            name='ledgersagastep',
            options={'permissions': [('can_view_ledger_saga_steps', 'Can view ledger saga steps')]},
        ),
        migrations.AlterModelOptions(
            name='ledgertransaction',
            options={'permissions': [('can_apply_raw_ledger_transaction', 'Can apply raw ledger transactions'), ('can_create_pending_ledger_transaction', 'Can create pending ledger transactions'), ('can_reverse_ledger_transaction', 'Can reverse ledger transactions'), ('can_impersonate_ledger_creator', 'Can set created_by to another user')]},
        ),
    ]
