# Generated by Django 5.1.6 on 2026-03-29 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0006_alter_ledgerentry_options_alter_ledgeroutbox_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgeroutbox',
            name='last_attempt_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='ledgeroutbox',
            name='last_redriven_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='ledgeroutbox',
            name='next_retry_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='ledgeroutbox',
            name='redrive_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='ledgeroutbox',
            index=models.Index(fields=['status', 'next_retry_at'], name='ledger_ledg_status_420e42_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgeroutbox',
            index=models.Index(fields=['status', 'dead_lettered_at'], name='ledger_ledg_status_c1d618_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgeroutbox',
            index=models.Index(fields=['status', 'last_attempt_at'], name='ledger_ledg_status_0ffd5e_idx'),
        ),
    ]
