# Generated by Django 5.1.6 on 2026-03-29 19:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0007_ledgeroutbox_last_attempt_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerHold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField()),
                ('reason', models.CharField(blank=True, default='', max_length=128)),
                ('released', models.BooleanField(db_index=True, default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('metadata_version', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('released_at', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                'permissions': [('can_manage_wallet_holds', 'Can manage wallet holds'), ('can_view_wallet_holds', 'Can view wallet holds')],
            },
        ),
        migrations.CreateModel(
            name='LedgerVelocityWindow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('transfer', 'Transfer'), ('purchase', 'Purchase')], db_index=True, max_length=32)),
                ('window_seconds', models.PositiveIntegerField(db_index=True)),
                ('amount', models.BigIntegerField(default=0)),
                ('count', models.PositiveIntegerField(default=0)),
                ('window_start', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'permissions': [('can_view_wallet_velocity', 'Can view wallet velocity windows')],
            },
        ),
        migrations.AddField(
            model_name='tokenwallet',
            name='daily_inflow_limit',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tokenwallet',
            name='daily_outflow_limit',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tokenwallet',
            name='held_balance',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tokenwallet',
            name='hourly_inflow_limit',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tokenwallet',
            name='hourly_outflow_limit',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tokenwallet',
            name='review_required',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='tokenwallet',
            name='risk_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='tokenwallet',
            name='risk_status',
            field=models.CharField(choices=[('clear', 'Clear'), ('review', 'Review'), ('blocked', 'Blocked')], db_index=True, default='clear', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='tokenwallet',
            constraint=models.CheckConstraint(condition=models.Q(('held_balance__gte', 0)), name='tokenwallet_held_balance_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='tokenwallet',
            constraint=models.CheckConstraint(condition=models.Q(('balance__gte', models.F('held_balance')), ('allow_negative', True), _connector='OR'), name='tokenwallet_balance_gte_held_balance_if_not_negative'),
        ),
        migrations.AddField(
            model_name='ledgerhold',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_holds_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ledgerhold',
            name='released_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_holds_released', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ledgerhold',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holds', to='ledger.tokenwallet'),
        ),
        migrations.AddField(
            model_name='ledgervelocitywindow',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='velocity_windows', to='ledger.tokenwallet'),
        ),
        migrations.AddIndex(
            model_name='ledgerhold',
            index=models.Index(fields=['wallet', 'released', 'created_at'], name='ledger_ledg_wallet__2cb95c_idx'),
        ),
        migrations.AddConstraint(
            model_name='ledgerhold',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='ledgerhold_amount_gt_0'),
        ),
        migrations.AddIndex(
            model_name='ledgervelocitywindow',
            index=models.Index(fields=['wallet', 'action', 'window_seconds', 'window_start'], name='ledger_ledg_wallet__0ecc4f_idx'),
        ),
        migrations.AddConstraint(
            model_name='ledgervelocitywindow',
            constraint=models.UniqueConstraint(fields=('wallet', 'action', 'window_seconds', 'window_start'), name='ledgervelocitywindow_unique_wallet_action_window'),
        ),
        migrations.AddConstraint(
            model_name='ledgervelocitywindow',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='ledgervelocitywindow_amount_gte_0'),
        ),
    ]
