# Generated by Django 5.1.6 on 2026-04-05 16:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0008_ledgerhold_ledgervelocitywindow_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal')], db_index=True, max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('canceled', 'Canceled'), ('completed', 'Completed')], db_index=True, default='pending', max_length=16)),
                ('amount', models.BigIntegerField()),
                ('asset_code', models.CharField(default='TOKENS', max_length=16)),
                ('destination_address', models.CharField(blank=True, max_length=255)),
                ('reference', models.CharField(db_index=True, max_length=64, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('metadata_version', models.PositiveIntegerField(default=1)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_requests_created', to=settings.AUTH_USER_MODEL)),
                ('hold', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_request', to='ledger.ledgerhold')),
                ('linked_ledger_txn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wallet_requests', to='ledger.ledgertransaction')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_requests_reviewed', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wallet_requests', to='ledger.tokenwallet')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'permissions': [('can_manage_wallet_requests', 'Can manage wallet requests'), ('can_review_wallet_requests', 'Can review wallet requests')],
                'indexes': [models.Index(fields=['wallet', 'status', 'created_at'], name='ledger_wall_wallet__ff5fd4_idx'), models.Index(fields=['wallet', 'request_type', 'created_at'], name='ledger_wall_wallet__d45216_idx')],
            },
        ),
    ]
