# Generated by Django 5.1.6 on 2026-04-06 09:38

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0010_alter_tokenwallet_system_key_depositaddress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('chain', models.CharField(db_index=True, max_length=32)),
                ('asset_code', models.CharField(db_index=True, max_length=32)),
                ('token_contract_address', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('deposit_address', models.CharField(max_length=128, unique=True)),
                ('address_derivation_ref', models.CharField(max_length=128, unique=True)),
                ('status', models.CharField(choices=[('awaiting_payment', 'Awaiting payment'), ('seen_onchain', 'Seen on-chain'), ('confirming', 'Confirming'), ('credited', 'Credited'), ('expired', 'Expired'), ('failed', 'Failed')], db_index=True, default='awaiting_payment', max_length=32)),
                ('min_amount', models.BigIntegerField(default=1)),
                ('required_confirmations', models.PositiveIntegerField(default=1)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('observed_txid', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('observed_amount', models.BigIntegerField(blank=True, null=True)),
                ('confirmations', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('metadata_version', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposit_sessions_created', to=settings.AUTH_USER_MODEL)),
                ('credited_ledger_txn', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credited_deposit_session', to='ledger.ledgertransaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deposit_sessions', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deposit_sessions', to='ledger.tokenwallet')),
            ],
            options={
                'permissions': [('can_manage_deposit_sessions', 'Can manage deposit sessions'), ('can_view_deposit_sessions', 'Can view deposit sessions'), ('can_credit_confirmed_deposits', 'Can credit confirmed deposits')],
            },
        ),
        migrations.AddField(
            model_name='depositaddress',
            name='allocated_deposit_session',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='allocated_address',
                to='ledger.depositsession',
            ),
        ),
        migrations.CreateModel(
            name='ObservedOnchainTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(max_length=160, unique=True)),
                ('chain', models.CharField(db_index=True, max_length=32)),
                ('txid', models.CharField(db_index=True, max_length=128)),
                ('log_index', models.BigIntegerField(blank=True, null=True)),
                ('block_number', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('from_address', models.CharField(blank=True, default='', max_length=128)),
                ('to_address', models.CharField(db_index=True, max_length=128)),
                ('token_contract_address', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('asset_code', models.CharField(db_index=True, max_length=32)),
                ('amount', models.BigIntegerField()),
                ('confirmations', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('observed', 'Observed'), ('confirming', 'Confirming'), ('confirmed', 'Confirmed'), ('credited', 'Credited'), ('ignored', 'Ignored'), ('failed', 'Failed')], db_index=True, default='observed', max_length=16)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('metadata_version', models.PositiveSmallIntegerField(default=1)),
                ('first_seen_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('confirmed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credited_ledger_txn', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credited_onchain_transfer', to='ledger.ledgertransaction')),
                ('deposit_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='observed_transfers', to='ledger.depositsession')),
            ],
            options={
                'permissions': [('can_record_onchain_observations', 'Can record on-chain observations'), ('can_view_onchain_transfers', 'Can view on-chain transfers')],
            },
        ),
        migrations.AddIndex(
            model_name='depositsession',
            index=models.Index(fields=['user', 'status', '-created_at'], name='ledger_depo_user_id_fe4e5b_idx'),
        ),
        migrations.AddIndex(
            model_name='depositsession',
            index=models.Index(fields=['wallet', 'status', '-created_at'], name='ledger_depo_wallet__329a64_idx'),
        ),
        migrations.AddIndex(
            model_name='depositsession',
            index=models.Index(fields=['chain', 'asset_code', 'status'], name='ledger_depo_chain_ae4354_idx'),
        ),
        migrations.AddIndex(
            model_name='depositsession',
            index=models.Index(fields=['expires_at', 'status'], name='ledger_depo_expires_a4c510_idx'),
        ),
        migrations.AddConstraint(
            model_name='depositsession',
            constraint=models.CheckConstraint(condition=models.Q(('min_amount__gt', 0)), name='depositsession_min_amount_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='depositsession',
            constraint=models.CheckConstraint(condition=models.Q(('required_confirmations__gte', 1)), name='depositsession_required_confirmations_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='depositsession',
            constraint=models.CheckConstraint(condition=models.Q(('confirmations__gte', 0)), name='depositsession_confirmations_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='depositsession',
            constraint=models.CheckConstraint(condition=models.Q(('observed_amount__isnull', True), ('observed_amount__gt', 0), _connector='OR'), name='depositsession_observed_amount_gt_0_if_present'),
        ),
        migrations.AddIndex(
            model_name='observedonchaintransfer',
            index=models.Index(fields=['chain', 'txid'], name='ledger_obse_chain_af5967_idx'),
        ),
        migrations.AddIndex(
            model_name='observedonchaintransfer',
            index=models.Index(fields=['chain', 'to_address', 'status'], name='ledger_obse_chain_f7d97d_idx'),
        ),
        migrations.AddIndex(
            model_name='observedonchaintransfer',
            index=models.Index(fields=['deposit_session', 'status'], name='ledger_obse_deposit_8e5bdc_idx'),
        ),
        migrations.AddIndex(
            model_name='observedonchaintransfer',
            index=models.Index(fields=['status', 'first_seen_at'], name='ledger_obse_status_af2474_idx'),
        ),
        migrations.AddConstraint(
            model_name='observedonchaintransfer',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='observedonchaintransfer_amount_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='observedonchaintransfer',
            constraint=models.CheckConstraint(condition=models.Q(('confirmations__gte', 0)), name='observedonchaintransfer_confirmations_gte_0'),
        ),
    ]
