# Generated by Django 5.1.6 on 2026-04-06 10:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0011_depositsession_observedonchaintransfer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalAPIRequestNonce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(db_index=True, max_length=64)),
                ('nonce', models.CharField(max_length=128)),
                ('request_sha256', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'indexes': [models.Index(fields=['service_name', 'created_at'], name='ledger_inte_service_1324d1_idx'), models.Index(fields=['expires_at'], name='ledger_inte_expires_64c258_idx')],
                'constraints': [models.UniqueConstraint(fields=('service_name', 'nonce'), name='uniq_internalapirequestnonce_service_nonce')],
            },
        ),
    ]
