# Generated by Django 5.1.6 on 2026-04-06 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0012_internalapirequestnonce'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositaddress',
            name='derivation_index',
            field=models.PositiveBigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='depositaddress',
            constraint=models.UniqueConstraint(condition=models.Q(('derivation_index__isnull', False)), fields=('chain', 'asset_code', 'token_contract_address', 'derivation_index'), name='uniq_depositaddress_option_derivation_index'),
        ),
    ]
