# Generated by Django 5.1.6 on 2026-04-06 17:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0013_depositaddress_derivation_index_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositSweepJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('chain', models.CharField(db_index=True, max_length=32)),
                ('asset_code', models.CharField(db_index=True, max_length=32)),
                ('token_contract_address', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('source_address', models.CharField(db_index=True, max_length=128)),
                ('address_derivation_ref', models.CharField(max_length=128)),
                ('derivation_index', models.PositiveBigIntegerField(blank=True, db_index=True, null=True)),
                ('amount', models.BigIntegerField()),
                ('destination_address', models.CharField(blank=True, default='', max_length=128)),
                ('gas_funding_txid', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('sweep_txid', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('funding_broadcasted', 'Funding broadcasted'), ('ready_to_sweep', 'Ready to sweep'), ('sweep_broadcasted', 'Sweep broadcasted'), ('confirmed', 'Confirmed'), ('failed', 'Failed'), ('abandoned', 'Abandoned')], db_index=True, default='pending', max_length=32)),
                ('claimed_by_service', models.CharField(blank=True, default='', max_length=64)),
                ('claim_expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('metadata_version', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deposit_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sweep_jobs', to='ledger.depositsession')),
                ('observed_transfer', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sweep_job', to='ledger.observedonchaintransfer')),
            ],
            options={
                'permissions': [('can_manage_deposit_sweep_jobs', 'Can manage deposit sweep jobs'), ('can_view_deposit_sweep_jobs', 'Can view deposit sweep jobs')],
                'indexes': [models.Index(fields=['status', 'chain', 'asset_code'], name='ledger_depo_status_c11a02_idx'), models.Index(fields=['status', 'claim_expires_at'], name='ledger_depo_status_0ec8d0_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='depositsweepjob_amount_gt_0')],
            },
        ),
    ]
