# Generated by Django 5.1.6 on 2026-04-11 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0014_depositsweepjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositsession',
            name='status',
            field=models.CharField(choices=[('awaiting_payment', 'Awaiting payment'), ('seen_onchain', 'Seen on-chain'), ('confirming', 'Confirming'), ('credited', 'Credited'), ('expired', 'Expired'), ('failed', 'Failed'), ('canceled', 'canceled')], db_index=True, default='awaiting_payment', max_length=32),
        ),
    ]
