# Generated by Django 5.1.6 on 2026-04-12 13:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0015_alter_depositsession_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='depositsession',
            name='swept_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='depositsession',
            name='status',
            field=models.CharField(choices=[('awaiting_payment', 'Awaiting payment'), ('seen_onchain', 'Seen on-chain'), ('confirming', 'Confirming'), ('credited', 'Credited'), ('swept', 'Swept'), ('expired', 'Expired'), ('failed', 'Failed'), ('canceled', 'Canceled')], db_index=True, default='awaiting_payment', max_length=32),
        ),
        migrations.AddIndex(
            model_name='depositsession',
            index=models.Index(fields=['status', 'swept_at'], name='ledger_depo_status_9852da_idx'),
        ),
    ]
