# Generated by Django 5.1.6 on 2026-04-12 15:57

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0016_depositsession_swept_at_alter_depositsession_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositRouteCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_key', models.CharField(max_length=96, unique=True)),
                ('chain', models.CharField(db_index=True, max_length=32)),
                ('asset_code', models.CharField(db_index=True, max_length=32)),
                ('token_contract_address', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('next_derivation_index', models.PositiveBigIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('metadata_version', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='depositsession',
            name='derivation_index',
            field=models.PositiveBigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='depositsession',
            name='derivation_path',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='depositsession',
            name='display_label',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='depositsession',
            name='route_key',
            field=models.CharField(db_index=True, default='', max_length=96),
        ),
        migrations.AddIndex(
            model_name='depositsession',
            index=models.Index(fields=['route_key', 'status', '-created_at'], name='ledger_depo_route_k_fafb83_idx'),
        ),
        migrations.AddIndex(
            model_name='depositsession',
            index=models.Index(fields=['route_key', 'derivation_index'], name='ledger_depo_route_k_38be2b_idx'),
        ),
        migrations.AddConstraint(
            model_name='depositsession',
            constraint=models.CheckConstraint(condition=models.Q(('derivation_index__isnull', True), ('derivation_index__gte', 0), _connector='OR'), name='depositsession_derivation_index_gte_0_if_present'),
        ),
        migrations.AddIndex(
            model_name='depositroutecounter',
            index=models.Index(fields=['chain', 'asset_code'], name='ledger_depo_chain_046081_idx'),
        ),
        migrations.AddIndex(
            model_name='depositroutecounter',
            index=models.Index(fields=['chain', 'asset_code', 'token_contract_address'], name='ledger_depo_chain_608140_idx'),
        ),
        migrations.AddConstraint(
            model_name='depositroutecounter',
            constraint=models.CheckConstraint(condition=models.Q(('next_derivation_index__gte', 0)), name='depositroutecounter_next_derivation_index_gte_0'),
        ),
    ]
