# Generated by Django 5.1.6 on 2026-04-15 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0017_depositroutecounter_depositsession_derivation_index_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='observedonchaintransfer',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='observedonchaintransfer',
            name='observedonchaintransfer_amount_gt_0',
        ),
        migrations.RemoveConstraint(
            model_name='observedonchaintransfer',
            name='observedonchaintransfer_confirmations_gte_0',
        ),
        migrations.RemoveIndex(
            model_name='observedonchaintransfer',
            name='ledger_obse_chain_af5967_idx',
        ),
        migrations.RemoveIndex(
            model_name='observedonchaintransfer',
            name='ledger_obse_chain_f7d97d_idx',
        ),
        migrations.RemoveIndex(
            model_name='observedonchaintransfer',
            name='ledger_obse_deposit_8e5bdc_idx',
        ),
        migrations.RemoveIndex(
            model_name='observedonchaintransfer',
            name='ledger_obse_status_af2474_idx',
        ),
        migrations.RemoveField(
            model_name='observedonchaintransfer',
            name='confirmed_at',
        ),
        migrations.RemoveField(
            model_name='observedonchaintransfer',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='observedonchaintransfer',
            name='credited_ledger_txn',
        ),
        migrations.RemoveField(
            model_name='observedonchaintransfer',
            name='deposit_session',
        ),
        migrations.RemoveField(
            model_name='observedonchaintransfer',
            name='first_seen_at',
        ),
        migrations.RemoveField(
            model_name='observedonchaintransfer',
            name='metadata_version',
        ),
        migrations.RemoveField(
            model_name='observedonchaintransfer',
            name='raw_payload',
        ),
        migrations.RemoveField(
            model_name='observedonchaintransfer',
            name='status',
        ),
        migrations.RemoveField(
            model_name='observedonchaintransfer',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='observedonchaintransfer',
            name='detected_block_number',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='observedonchaintransfer',
            name='detection_method',
            field=models.CharField(choices=[('event', 'Event'), ('balance_verification', 'Balance verification')], db_index=True, default='event', max_length=32),
        ),
        migrations.AlterField(
            model_name='observedonchaintransfer',
            name='txid',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
    ]
