# Generated by Django 5.1.6 on 2026-04-16 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0018_alter_observedonchaintransfer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='observedonchaintransfer',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='observedonchaintransfer',
            name='credited_ledger_txn',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credited_onchain_transfer', to='ledger.ledgertransaction'),
        ),
        migrations.AddField(
            model_name='observedonchaintransfer',
            name='deposit_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='observed_transfers', to='ledger.depositsession'),
        ),
        migrations.AddField(
            model_name='observedonchaintransfer',
            name='metadata_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='observedonchaintransfer',
            name='raw_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='observedonchaintransfer',
            name='status',
            field=models.CharField(choices=[('observed', 'Observed'), ('confirming', 'Confirming'), ('confirmed', 'Confirmed'), ('credited', 'Credited')], db_index=True, default='observed', max_length=32),
        ),
        migrations.AlterField(
            model_name='observedonchaintransfer',
            name='asset_code',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='observedonchaintransfer',
            name='block_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='observedonchaintransfer',
            name='chain',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='observedonchaintransfer',
            name='detected_block_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='observedonchaintransfer',
            name='detection_method',
            field=models.CharField(default='event', max_length=32),
        ),
        migrations.AlterField(
            model_name='observedonchaintransfer',
            name='event_key',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='observedonchaintransfer',
            name='from_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='observedonchaintransfer',
            name='log_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='observedonchaintransfer',
            name='to_address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='observedonchaintransfer',
            name='token_contract_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='observedonchaintransfer',
            name='txid',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
