# Generated by Django 5.1.6 on 2026-04-16 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0020_backfill_observed_transfer_deposit_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observedonchaintransfer',
            name='deposit_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observed_transfers', to='ledger.depositsession'),
        ),
    ]
