# Generated by Django 5.1.6 on 2026-04-16 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0021_alter_observedonchaintransfer_deposit_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgertransaction',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
