# Generated by Django 5.1.6 on 2026-04-19 11:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0022_alter_ledgertransaction_external_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenPack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(blank=True, default='', max_length=128)),
                ('badge_text', models.CharField(blank=True, default='', max_length=24)),
                ('token_amount', models.BigIntegerField()),
                ('gross_stable_amount', models.BigIntegerField()),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('metadata_version', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('sort_order', 'id'),
                'constraints': [models.CheckConstraint(condition=models.Q(('token_amount__gt', 0)), name='tokenpack_token_amount_gt_0'), models.CheckConstraint(condition=models.Q(('gross_stable_amount__gt', 0)), name='tokenpack_gross_stable_amount_gt_0')],
            },
        ),
    ]
