# Generated by Django 5.1.6 on 2026-04-23 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0023_tokenpack'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletrequest',
            name='payout_txid',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
    ]
