# Generated by Django 5.1.6 on 2026-04-25 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0024_walletrequest_payout_txid'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositsweepjob',
            name='last_error_code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='depositsweepjob',
            name='last_error_retryable',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='depositsweepjob',
            name='last_sweep_gas_limit',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='depositsweepjob',
            name='next_retry_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='depositsweepjob',
            name='retry_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='depositsweepjob',
            index=models.Index(fields=['status', 'next_retry_at'], name='ledger_depo_status_62cfd0_idx'),
        ),
    ]
