# Generated by Django 5.1.6 on 2026-04-26 09:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0025_depositsweepjob_last_error_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvmSenderState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain', models.CharField(db_index=True, max_length=32)),
                ('address', models.CharField(db_index=True, max_length=128)),
                ('next_nonce', models.PositiveBigIntegerField(blank=True, null=True)),
                ('locked_by_service', models.CharField(blank=True, default='', max_length=64)),
                ('lock_token', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('lock_expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('metadata_version', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'permissions': [('can_manage_evm_sender_states', 'Can manage EVM sender nonce locks'), ('can_view_evm_sender_states', 'Can view EVM sender nonce locks')],
            },
        ),
        migrations.AddField(
            model_name='depositsweepjob',
            name='claim_token',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddIndex(
            model_name='depositsweepjob',
            index=models.Index(fields=['claimed_by_service', 'claim_token'], name='ledger_depo_claimed_97caa0_idx'),
        ),
        migrations.AddIndex(
            model_name='evmsenderstate',
            index=models.Index(fields=['chain', 'address'], name='ledger_evms_chain_4066dc_idx'),
        ),
        migrations.AddIndex(
            model_name='evmsenderstate',
            index=models.Index(fields=['lock_expires_at'], name='ledger_evms_lock_ex_85aff9_idx'),
        ),
        migrations.AddConstraint(
            model_name='evmsenderstate',
            constraint=models.UniqueConstraint(fields=('chain', 'address'), name='uniq_evmsenderstate_chain_address'),
        ),
        migrations.AddConstraint(
            model_name='evmsenderstate',
            constraint=models.CheckConstraint(condition=models.Q(('next_nonce__isnull', True), ('next_nonce__gte', 0), _connector='OR'), name='evmsenderstate_next_nonce_gte_0_if_present'),
        ),
    ]
