# Generated by Django 5.1.6 on 2026-04-26 13:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0026_evmsenderstate_depositsweepjob_claim_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrphanDepositRecoveryAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain', models.CharField(db_index=True, max_length=32)),
                ('asset_code', models.CharField(db_index=True, max_length=32)),
                ('token_contract_address', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('deposit_address', models.CharField(db_index=True, max_length=128)),
                ('address_derivation_ref', models.CharField(blank=True, default='', max_length=128)),
                ('derivation_index', models.PositiveBigIntegerField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('pending_check', 'Pending check'), ('retryable_error', 'Retryable error'), ('empty_final', 'Empty final'), ('dust_final', 'Dust final'), ('ignored_final', 'Ignored final'), ('swept_token_final', 'Swept token final'), ('swept_native_final', 'Swept native final'), ('swept_both_final', 'Swept both final')], db_index=True, default='pending_check', max_length=32)),
                ('decision_reason', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('last_token_balance', models.BigIntegerField(default=0)),
                ('last_native_balance', models.BigIntegerField(default=0)),
                ('last_token_value_usd', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('last_native_value_usd', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('last_estimated_token_recovery_cost_usd', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('last_estimated_native_recovery_cost_usd', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('funding_txid', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('token_sweep_txid', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('native_sweep_txid', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('last_error', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('metadata_version', models.PositiveSmallIntegerField(default=1)),
                ('last_checked_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('finalized_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deposit_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orphan_recovery_audits', to='ledger.depositsession')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'last_checked_at'], name='ledger_orph_status_072fa8_idx'), models.Index(fields=['chain', 'asset_code', 'status'], name='ledger_orph_chain_6c3e85_idx'), models.Index(fields=['finalized_at'], name='ledger_orph_finaliz_294cc9_idx')],
                'constraints': [models.UniqueConstraint(fields=('chain', 'deposit_address'), name='orphanrecoveryaudit_unique_chain_address'), models.CheckConstraint(condition=models.Q(('derivation_index__isnull', True), ('derivation_index__gte', 0), _connector='OR'), name='orphanrecoveryaudit_derivation_index_gte_0_if_present')],
            },
        ),
    ]
