# Generated by Django 5.1.6 on 2026-05-01 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0027_orphandepositrecoveryaudit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='observedonchaintransfer',
            options={'permissions': [('can_record_onchain_observations', 'Can record on-chain observations'), ('can_view_onchain_transfers', 'Can view on-chain transfers')]},
        ),
    ]
