# Generated by Django 5.1.6 on 2026-05-05 21:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0028_add_observed_onchain_transfer_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='depositsession',
            name='expected_onchain_raw_amount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=78, null=True),
        ),
        migrations.AddField(
            model_name='depositsweepjob',
            name='onchain_raw_amount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=78, null=True),
        ),
        migrations.AddField(
            model_name='observedonchaintransfer',
            name='onchain_raw_amount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=78, null=True),
        ),
        migrations.AddConstraint(
            model_name='depositsession',
            constraint=models.CheckConstraint(condition=models.Q(('expected_onchain_raw_amount__isnull', True), ('expected_onchain_raw_amount__gt', 0), _connector='OR'), name='depositsession_expected_raw_amount_gt_0_if_present'),
        ),
        migrations.AddConstraint(
            model_name='depositsweepjob',
            constraint=models.CheckConstraint(condition=models.Q(('onchain_raw_amount__isnull', True), ('onchain_raw_amount__gt', 0), _connector='OR'), name='depositsweepjob_raw_amount_gt_0_if_present'),
        ),
        migrations.AddConstraint(
            model_name='observedonchaintransfer',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='observedtransfer_amount_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='observedonchaintransfer',
            constraint=models.CheckConstraint(condition=models.Q(('onchain_raw_amount__isnull', True), ('onchain_raw_amount__gt', 0), _connector='OR'), name='observedtransfer_raw_amount_gt_0_if_present'),
        ),
    ]
