# Generated by Django 5.1.6 on 2026-05-14 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0029_depositsession_expected_onchain_raw_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ledgertransaction',
            options={'permissions': [('can_apply_raw_ledger_transaction', 'Can apply raw ledger transactions'), ('can_create_pending_ledger_transaction', 'Can create pending ledger transactions'), ('can_reverse_ledger_transaction', 'Can reverse ledger transactions'), ('can_impersonate_ledger_creator', 'Can set created_by to another user'), ('can_book_platform_fee_adjustments', 'Can book platform fee adjustments')]},
        ),
        migrations.AlterField(
            model_name='tokenwallet',
            name='system_key',
            field=models.CharField(blank=True, choices=[('issuance', 'Issuance'), ('platform_fees', 'Platform fees'), ('external_asset_clearing', 'External asset clearing'), ('orphans_recovered', 'Orphans recovered')], max_length=32, null=True, unique=True),
        ),
    ]
