# Generated by Django 5.1.6 on 2026-05-14 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0030_alter_ledgertransaction_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreasuryBalance',
            fields=[
            ],
            options={
                'verbose_name': 'Treasury balance',
                'verbose_name_plural': 'Treasury balances',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ledger.tokenwallet',),
        ),
    ]
