# Generated by Django 5.1.6 on 2026-05-14 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0031_treasurybalance'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreasuryMetric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_key', models.CharField(max_length=64, unique=True)),
                ('label', models.CharField(max_length=128)),
                ('amount', models.BigIntegerField(default=0)),
                ('unit', models.CharField(choices=[('platform_token', 'Platform token'), ('stable', 'Stable')], default='platform_token', max_length=32)),
                ('display_order', models.PositiveIntegerField(default=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Treasury metric',
                'verbose_name_plural': 'Treasury metrics',
                'ordering': ('display_order', 'metric_key'),
            },
        ),
        migrations.DeleteModel(
            name='TreasuryBalance',
        ),
    ]
