# Generated by Django 5.1.6 on 2026-07-06 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0032_treasurymetric_delete_treasurybalance'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenpack',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='wallet/token_packs/'),
        ),
    ]
