# Generated by Django 5.1.6 on 2026-07-24 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0033_tokenpack_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tokenpack',
            name='image',
        ),
    ]
