# Generated by Django 5.1.6 on 2026-08-30 09:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0037_weekly_share_quests'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerentry',
            name='promotional_delta',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tokenwallet',
            name='promotional_balance',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(('promotional_delta', 0), models.Q(('delta__gt', 0), ('promotional_delta__gt', 0), ('promotional_delta__lte', models.F('delta'))), models.Q(('delta__lt', 0), ('promotional_delta__lt', 0), ('promotional_delta__gte', models.F('delta'))), _connector='OR'), name='ledgerentry_promotional_delta_valid'),
        ),
        migrations.AddConstraint(
            model_name='tokenwallet',
            constraint=models.CheckConstraint(condition=models.Q(('promotional_balance__gte', 0)), name='tokenwallet_promotional_balance_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='tokenwallet',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('promotional_balance', 0), ('wallet_type', 'system')), models.Q(('allow_negative', True), ('promotional_balance', 0), ('wallet_type', 'user')), models.Q(('wallet_type', 'user'), ('balance__gte', models.F('promotional_balance'))), _connector='OR'), name='tokenwallet_promotional_balance_valid'),
        ),
    ]
