# Generated by Django 5.1.6 on 2026-08-31 15:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0038_ledgerentry_promotional_delta_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerentry',
            name='restricted_promotional_delta',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tokenwallet',
            name='restricted_promotional_balance',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(('restricted_promotional_delta', 0), models.Q(('promotional_delta__gt', 0), ('restricted_promotional_delta__gt', 0), ('restricted_promotional_delta__lte', models.F('promotional_delta'))), models.Q(('promotional_delta__lt', 0), ('restricted_promotional_delta__lt', 0), ('restricted_promotional_delta__gte', models.F('promotional_delta'))), _connector='OR'), name='ledgerentry_restricted_promotional_delta_valid'),
        ),
        migrations.AddConstraint(
            model_name='tokenwallet',
            constraint=models.CheckConstraint(condition=models.Q(('restricted_promotional_balance__gte', 0)), name='tokenwallet_restricted_promotional_balance_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='tokenwallet',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('restricted_promotional_balance', 0), ('wallet_type', 'system')), models.Q(('wallet_type', 'user'), ('promotional_balance__gte', models.F('restricted_promotional_balance'))), _connector='OR'), name='tokenwallet_restricted_promotional_balance_valid'),
        ),
    ]
