# Generated by Django 5.1.6 on 2026-08-31 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0039_ledgerentry_restricted_promotional_delta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletrequest',
            name='payout_asset_code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='walletrequest',
            name='payout_chain',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32),
        ),
    ]
