# Generated by Django 5.1.6 on 2026-08-31 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0040_walletrequest_payout_asset_code_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='questqualifiedvisit',
            name='quest_visit_cycle_visitor_unique',
        ),
        migrations.RemoveConstraint(
            model_name='questqualifiedvisit',
            name='quest_visit_cycle_network_unique',
        ),
        migrations.RemoveConstraint(
            model_name='questqualifiedvisit',
            name='quest_visit_cycle_fp_unique',
        ),
        migrations.AddConstraint(
            model_name='questqualifiedvisit',
            constraint=models.UniqueConstraint(fields=('campaign', 'visitor_hash'), name='quest_visit_campaign_vid_uniq'),
        ),
        migrations.AddConstraint(
            model_name='questqualifiedvisit',
            constraint=models.UniqueConstraint(fields=('campaign', 'fingerprint_hash'), name='quest_visit_campaign_fp_uniq'),
        ),
    ]
