# Generated by Django 5.1.6 on 2026-09-04 21:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0041_remove_questqualifiedvisit_quest_visit_cycle_visitor_unique_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='P2PMakerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('suspended', 'Suspended'), ('banned', 'Banned')], db_index=True, default='paused', max_length=16)),
                ('accepting_orders', models.BooleanField(db_index=True, default=False)),
                ('paypal_enabled', models.BooleanField(default=False)),
                ('revolut_enabled', models.BooleanField(default=False)),
                ('sepa_enabled', models.BooleanField(default=False)),
                ('wise_enabled', models.BooleanField(default=False)),
                ('bank_transfer_enabled', models.BooleanField(default=False)),
                ('min_order_amount', models.PositiveBigIntegerField(default=0)),
                ('max_order_amount', models.PositiveBigIntegerField(blank=True, null=True)),
                ('commission_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('max_concurrent_orders', models.PositiveSmallIntegerField(default=1)),
                ('last_assigned_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('completed_orders', models.PositiveBigIntegerField(default=0)),
                ('canceled_orders', models.PositiveBigIntegerField(default=0)),
                ('disputed_orders', models.PositiveBigIntegerField(default=0)),
                ('avg_response_time_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('avg_completion_time_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('rating_count', models.PositiveBigIntegerField(default=0)),
                ('total_volume', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='p2p_maker_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='P2POrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('payment_method', models.CharField(choices=[('paypal', 'PayPal'), ('revolut', 'Revolut'), ('sepa', 'SEPA'), ('wise', 'Wise'), ('bank_transfer', 'Bank transfer')], db_index=True, max_length=24)),
                ('platform_amount', models.PositiveBigIntegerField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('disputed', 'Disputed')], db_index=True, default='open', max_length=16)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='p2p_buyer_orders', to=settings.AUTH_USER_MODEL)),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='ledger.p2pmakerprofile')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='P2PMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('user', 'User'), ('system', 'System')], default='user', max_length=12)),
                ('body', models.TextField(max_length=4000)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='p2p_messages', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ledger.p2porder')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AddIndex(
            model_name='p2pmakerprofile',
            index=models.Index(fields=['status', 'accepting_orders', 'last_assigned_at'], name='p2p_maker_pool_idx'),
        ),
        migrations.AddConstraint(
            model_name='p2pmakerprofile',
            constraint=models.CheckConstraint(condition=models.Q(('max_order_amount__isnull', True), ('max_order_amount__gte', models.F('min_order_amount')), _connector='OR'), name='p2p_maker_max_order_gte_min'),
        ),
        migrations.AddConstraint(
            model_name='p2pmakerprofile',
            constraint=models.CheckConstraint(condition=models.Q(('commission_percent__gte', 0), ('commission_percent__lte', 100)), name='p2p_maker_commission_pct_0_100'),
        ),
        migrations.AddConstraint(
            model_name='p2pmakerprofile',
            constraint=models.CheckConstraint(condition=models.Q(('max_concurrent_orders__gt', 0)), name='p2p_maker_concurrency_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='p2pmakerprofile',
            constraint=models.CheckConstraint(condition=models.Q(('rating__isnull', True), models.Q(('rating__gte', 0), ('rating__lte', 5)), _connector='OR'), name='p2p_maker_rating_0_5'),
        ),
        migrations.AddIndex(
            model_name='p2porder',
            index=models.Index(fields=['maker', 'status', 'created_at'], name='p2p_order_maker_status_idx'),
        ),
        migrations.AddIndex(
            model_name='p2porder',
            index=models.Index(fields=['buyer', 'status', 'created_at'], name='p2p_order_buyer_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='p2porder',
            constraint=models.CheckConstraint(condition=models.Q(('platform_amount__gt', 0)), name='p2p_order_platform_amount_gt_0'),
        ),
        migrations.AddIndex(
            model_name='p2pmessage',
            index=models.Index(fields=['order', 'id'], name='p2p_message_order_id_idx'),
        ),
    ]
