# Generated by Django 5.1.6 on 2026-09-05 15:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0042_p2pmakerprofile_p2porder_p2pmessage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='p2pmakerprofile',
            name='card_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='p2pmakerprofile',
            name='discord_user_id',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='p2pmakerprofile',
            name='telegram_user_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='p2porder',
            name='accepted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='p2porder',
            name='base_amount',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='p2porder',
            name='buyer_marked_paid_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='p2porder',
            name='commission_amount',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='p2porder',
            name='commission_percent_snapshot',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='p2porder',
            name='completed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='p2porder',
            name='dispute_resolution',
            field=models.CharField(blank=True, choices=[('', 'Unresolved'), ('customer_wins', 'Customer wins'), ('agent_wins', 'P2P agent wins')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='p2porder',
            name='disputed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='p2porder',
            name='funded_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='p2porder',
            name='funding_txn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='p2p_funding_orders', to='ledger.ledgertransaction'),
        ),
        migrations.AddField(
            model_name='p2porder',
            name='resolved_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='p2porder',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='p2p_disputes_resolved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='p2porder',
            name='settlement_txn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='p2p_settlement_orders', to='ledger.ledgertransaction'),
        ),
        migrations.AddField(
            model_name='p2porder',
            name='token_amount',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='p2porder',
            name='token_pack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='p2p_orders', to='ledger.tokenpack'),
        ),
        migrations.AddField(
            model_name='p2porder',
            name='trade_expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='p2porder',
            name='maker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='ledger.p2pmakerprofile'),
        ),
        migrations.AlterField(
            model_name='p2porder',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Card'), ('apple_pay', 'Apple Pay'), ('google_pay', 'Google Pay'), ('paypal', 'PayPal'), ('revolut', 'Revolut'), ('sepa', 'SEPA'), ('wise', 'Wise'), ('bank_transfer', 'Bank transfer')], db_index=True, max_length=24),
        ),
        migrations.AlterField(
            model_name='p2porder',
            name='status',
            field=models.CharField(choices=[('open', 'Open (legacy)'), ('waiting_agent', 'Waiting for P2P agent'), ('waiting_new_agent', 'Waiting for a new P2P agent'), ('no_agent_available', 'No P2P agent available'), ('chat_open', 'Exchange open'), ('fiat_sent', 'Money sent'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('disputed', 'Disputed')], db_index=True, default='open', max_length=24),
        ),
        migrations.AlterField(
            model_name='tokenwallet',
            name='system_key',
            field=models.CharField(blank=True, choices=[('issuance', 'Issuance'), ('platform_fees', 'Platform fees'), ('p2p_settlement', 'P2P settlement'), ('external_asset_clearing', 'External asset clearing'), ('orphans_recovered', 'Orphans recovered')], max_length=32, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='P2PAgentAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('offered', 'Offered'), ('declined', 'Declined'), ('expired', 'Expired'), ('accepted', 'Accepted')], db_index=True, default='offered', max_length=16)),
                ('commission_percent_snapshot', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('commission_amount_snapshot', models.PositiveBigIntegerField(default=0)),
                ('transaction_amount_snapshot', models.PositiveBigIntegerField(default=0)),
                ('offered_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('responded_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='ledger.p2pmakerprofile')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='ledger.p2porder')),
            ],
            options={
                'ordering': ('offered_at', 'id'),
                'indexes': [models.Index(fields=['status', 'expires_at'], name='p2p_assignment_expiry_idx')],
                'constraints': [models.UniqueConstraint(fields=('order', 'maker'), name='p2p_assignment_order_maker_unique')],
            },
        ),
        migrations.CreateModel(
            name='P2PReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communication', models.PositiveSmallIntegerField()),
                ('responsiveness', models.PositiveSmallIntegerField()),
                ('reliability', models.PositiveSmallIntegerField()),
                ('payment_experience', models.PositiveSmallIntegerField()),
                ('cooperation', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='ledger.p2porder')),
                ('reviewee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='p2p_reviews_received', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='p2p_reviews_written', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'constraints': [models.UniqueConstraint(fields=('order', 'reviewer'), name='p2p_review_order_reviewer_unique'), models.CheckConstraint(condition=models.Q(('reviewer', models.F('reviewee')), _negated=True), name='p2p_review_distinct_users'), models.CheckConstraint(condition=models.Q(('communication__gte', 1), ('communication__lte', 5)), name='p2p_review_communication_1_5'), models.CheckConstraint(condition=models.Q(('responsiveness__gte', 1), ('responsiveness__lte', 5)), name='p2p_review_responsiveness_1_5'), models.CheckConstraint(condition=models.Q(('reliability__gte', 1), ('reliability__lte', 5)), name='p2p_review_reliability_1_5'), models.CheckConstraint(condition=models.Q(('payment_experience__gte', 1), ('payment_experience__lte', 5)), name='p2p_review_payment_1_5'), models.CheckConstraint(condition=models.Q(('cooperation__gte', 1), ('cooperation__lte', 5)), name='p2p_review_cooperation_1_5')],
            },
        ),
    ]
