# Generated by Django 5.1.6 on 2026-08-15 09:01

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ledger', '0037_weekly_share_quests'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdCampaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('placement', models.CharField(choices=[('home_leaderboard', 'Homepage banner · 728×90'), ('media_sidebar_rectangle', 'Video page sidebar · 300×250')], db_index=True, max_length=40)),
                ('creative', models.ImageField(upload_to='ads/creatives/%Y/%m/%d')),
                ('target_url', models.URLField(max_length=1000)),
                ('pricing_model', models.CharField(choices=[('cpm', 'CPM'), ('cpc', 'CPC')], db_index=True, max_length=8)),
                ('bid_microtokens', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('review_status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=16)),
                ('review_note', models.TextField(blank=True, default='')),
                ('delivery_status', models.CharField(choices=[('active', 'Active'), ('paused_user', 'Paused'), ('paused_funds', 'Paused · insufficient funds')], db_index=True, default='active', max_length=24)),
                ('impressions', models.PositiveBigIntegerField(default=0)),
                ('clicks', models.PositiveBigIntegerField(default=0)),
                ('spend_microtokens', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='AdSettlementBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_microtokens', models.PositiveBigIntegerField(default=0)),
                ('impressions', models.PositiveBigIntegerField(default=0)),
                ('clicks', models.PositiveBigIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('posted', 'Posted')], db_index=True, default='pending', max_length=12)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('posted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('redis_acked_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ad_settlement_batches', to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlement_batches', to='ads.adcampaign')),
                ('ledger_txn', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ad_settlement_batch', to='ledger.ledgertransaction')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='adcampaign',
            index=models.Index(fields=['placement', 'review_status', 'delivery_status'], name='ads_adcampa_placeme_0233a6_idx'),
        ),
        migrations.AddIndex(
            model_name='adcampaign',
            index=models.Index(fields=['advertiser', 'review_status', 'delivery_status'], name='ads_adcampa_adverti_85c5fe_idx'),
        ),
        migrations.AddConstraint(
            model_name='adcampaign',
            constraint=models.CheckConstraint(condition=models.Q(('bid_microtokens__gt', 0)), name='adcampaign_bid_positive'),
        ),
        migrations.AddIndex(
            model_name='adsettlementbatch',
            index=models.Index(fields=['campaign', 'redis_acked_at', 'created_at'], name='ads_adsettl_campaig_2685ff_idx'),
        ),
        migrations.AddIndex(
            model_name='adsettlementbatch',
            index=models.Index(fields=['status', 'redis_acked_at', 'created_at'], name='ads_adsettl_status_dc82a2_idx'),
        ),
    ]
