# Generated by Django 5.1.6 on 2026-08-15 12:35

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adcampaign',
            name='creative',
        ),
        migrations.CreateModel(
            name='AdCreative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('placement', models.CharField(choices=[('home_leaderboard', 'Homepage banner · 728×90'), ('media_sidebar_rectangle', 'Video page sidebar · 300×250')], db_index=True, max_length=40)),
                ('image', models.ImageField(upload_to='ads/creatives/%Y/%m/%d')),
                ('review_status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=16)),
                ('review_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_creatives', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='AdCampaignCreative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creative_links', to='ads.adcampaign')),
                ('creative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_links', to='ads.adcreative')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='creatives',
            field=models.ManyToManyField(blank=True, related_name='campaigns', through='ads.AdCampaignCreative', to='ads.adcreative'),
        ),
        migrations.AddConstraint(
            model_name='adcampaigncreative',
            constraint=models.UniqueConstraint(fields=('campaign', 'creative'), name='adcampaigncreative_unique_pair'),
        ),
        migrations.AddConstraint(
            model_name='adcampaigncreative',
            constraint=models.CheckConstraint(condition=models.Q(('weight__gt', 0)), name='adcampaigncreative_weight_positive'),
        ),
    ]
