# Generated by Django 5.1.6 on 2026-08-15 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_remove_adcampaign_creative_adcreative_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adcreative',
            name='destination_url',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='adcreative',
            name='vast_url',
            field=models.URLField(blank=True, default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='adcampaign',
            name='placement',
            field=models.CharField(choices=[('home_leaderboard', 'Banner · 728×90'), ('media_sidebar_rectangle', 'Banner · 300×250'), ('video_preroll', 'In-video · Preroll'), ('video_midroll', 'In-video · Midroll'), ('video_postroll', 'In-video · Postroll'), ('popunder', 'Popunder')], db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='adcampaign',
            name='target_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='adcreative',
            name='image',
            field=models.FileField(blank=True, upload_to='ads/creatives/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='adcreative',
            name='placement',
            field=models.CharField(choices=[('home_leaderboard', 'Banner · 728×90'), ('media_sidebar_rectangle', 'Banner · 300×250'), ('in_video', 'In-video · VAST (Preroll / Midroll / Postroll)'), ('popunder', 'Popunder · URL')], db_index=True, max_length=40),
        ),
    ]
