# Generated by Django 5.1.6 on 2026-08-21 06:22

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ledger', '0037_weekly_share_quests'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIGenerationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('prompt', models.TextField()),
                ('moderation', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], db_index=True, default='queued', max_length=16)),
                ('price_tokens', models.BigIntegerField()),
                ('provider', models.CharField(default='perchance', max_length=32)),
                ('provider_request_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('result_file', models.FileField(blank=True, upload_to='ai_generations/%Y/%m/%d/')),
                ('result_content_type', models.CharField(blank=True, default='', max_length=64)),
                ('result_metadata', models.JSONField(blank=True, default=dict)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('error_message', models.TextField(blank=True, default='')),
                ('claimed_by_service', models.CharField(blank=True, default='', max_length=64)),
                ('claim_token', models.CharField(blank=True, default='', max_length=64)),
                ('claim_expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('charged_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('charge_txn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ai_generation_charges', to='ledger.ledgertransaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ai_generation_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='AIGenerationRuntimeState',
            fields=[
                ('key', models.CharField(default='global', max_length=32, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_generation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ai_generation.aigenerationrequest')),
            ],
        ),
        migrations.AddIndex(
            model_name='aigenerationrequest',
            index=models.Index(fields=['user', 'status', '-created_at'], name='ai_generati_user_id_7fda88_idx'),
        ),
        migrations.AddIndex(
            model_name='aigenerationrequest',
            index=models.Index(fields=['status', 'created_at'], name='ai_generati_status_7b3d26_idx'),
        ),
        migrations.AddConstraint(
            model_name='aigenerationrequest',
            constraint=models.CheckConstraint(condition=models.Q(('price_tokens__gt', 0)), name='ai_generation_price_tokens_gt_0'),
        ),
    ]
