from django.urls import re_path

from . import subscription_views, views


urlpatterns = [
    re_path(
        r"^api/v1/creators/(?P<username>[\w.@+-]+)/subscription-plans$",
        subscription_views.creator_subscription_plans,
        name="premium_creator_subscription_plans",
    ),
    re_path(
        r"^api/v1/subscription-plans/(?P<plan_id>\d+)/subscribe$",
        subscription_views.subscribe_creator_plan,
        name="premium_subscription_subscribe",
    ),
    re_path(
        r"^api/v1/me/subscriptions$",
        subscription_views.my_creator_subscriptions,
        name="premium_my_subscriptions",
    ),
    re_path(
        r"^api/v1/subscriptions/(?P<subscription_id>\d+)/cancel$",
        subscription_views.cancel_subscription,
        name="premium_subscription_cancel",
    ),
    re_path(
        r"^api/v1/subscriptions/(?P<subscription_id>\d+)/resume$",
        subscription_views.resume_subscription,
        name="premium_subscription_resume",
    ),
    re_path(
        (
            r"^premium/media/"
            r"(?P<friendly_token>[\w\-_]*)/"
            r"upload/$"
        ),
        views.PremiumFineUploaderView.as_view(),
        name="premium_media_asset_upload",
    ),
    re_path(
        (
            r"^premium/media/"
            r"(?P<friendly_token>[\w\-_]*)/"
            r"upload/"
            r"(?P<upload_uuid>[a-fA-F0-9\-]{36})/"
            r"status/$"
        ),
        views.premium_upload_status,
        name="premium_media_asset_upload_status",
    ),
    re_path(
        (
            r"^premium/media/"
            r"(?P<friendly_token>[\w\-_]*)/"
            r"edit$"
        ),
        views.creator_premium_asset_edit,
        name="premium_media_asset_edit",
    ),
    re_path(
        (
            r"^api/v1/media/"
            r"(?P<friendly_token>[\w\-_]*)/"
            r"purchase$"
        ),
        views.purchase_media,
        name="premium_media_purchase",
    ),
    re_path(
        (
            r"^api/v1/media/"
            r"(?P<friendly_token>[\w\-_]*)/"
            r"premium-playback$"
        ),
        views.premium_playback,
        name="premium_media_playback",
    ),
    re_path(
        r"^api/v1/me/unlocked-media$",
        views.unlocked_media_api,
        name="premium_unlocked_media_api",
    ),
    re_path(
        r"^unlocked$",
        views.unlocked_media_page,
        name="premium_unlocked_media_page",
    ),
]
