# Generated by Django 5.1.6 on 2025-08-12 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0010_alter_encodeprofile_resolution'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, unique=True)),
                ('ordering', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Category group',
                'verbose_name_plural': 'Category groups',
                'ordering': ['ordering', 'title'],
            },
        ),
        migrations.AlterField(
            model_name='media',
            name='featured',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether your video is globally advertised on our featured page'),
        ),
        migrations.AddField(
            model_name='category',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='files.categorygroup'),
        ),
    ]
