# Generated by Django 5.1.6 on 2025-09-09 14:41

import django.db.models.deletion
import files.models
import imagekit.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0011_categorygroup_alter_media_featured_category_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CelebrityGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, unique=True)),
                ('ordering', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Celebrity group',
                'verbose_name_plural': 'Celebrity groups',
                'ordering': ['ordering', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Celebrity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default=files.models.generate_uid, max_length=36, unique=True)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(db_index=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_global', models.BooleanField(default=False, help_text='global celebrities or user specific')),
                ('media_count', models.IntegerField(default=0, help_text='number of media')),
                ('thumbnail', imagekit.models.fields.ProcessedImageField(blank=True, upload_to=files.models.celebrity_thumb_path)),
                ('listings_thumbnail', models.CharField(blank=True, help_text='Thumbnail to show on listings', max_length=400, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='celebrities', to='files.celebritygroup')),
            ],
            options={
                'verbose_name_plural': 'Celebrities',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='media',
            name='celebrities',
            field=models.ManyToManyField(blank=True, help_text='select one or more celebrities', to='files.celebrity'),
        ),
    ]
