# Generated by Django 5.1.6 on 2025-11-02 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0012_celebritygroup_celebrity_media_celebrities'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='dfans_video_url',
            field=models.URLField(blank=True, default='', verbose_name='DFans video URL'),
        ),
    ]
