# Generated by Django 5.1.6 on 2026-02-02 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0013_media_dfans_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='hls_hevc_file',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
