# Generated by Django 5.1.6 on 2026-06-26 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0014_media_hls_hevc_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='hls_av1_file',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='encodeprofile',
            name='codec',
            field=models.CharField(blank=True, choices=[('av1', 'av1'), ('h264', 'h264'), ('h265', 'h265'), ('vp9', 'vp9')], max_length=10, null=True),
        ),
    ]
