# Generated by Django 5.1.6 on 2026-06-29 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0016_enable_av1_disable_hevc'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaHLSRendition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codec', models.CharField(choices=[('h264', 'H.264'), ('h265', 'H.265 / HEVC'), ('av1', 'AV1')], db_index=True, max_length=16)),
                ('resolution', models.PositiveIntegerField(db_index=True)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('master_file', models.CharField(max_length=1000)),
                ('playlist_file', models.CharField(max_length=1000)),
                ('iframe_file', models.CharField(blank=True, max_length=1000)),
                ('bandwidth', models.PositiveIntegerField(blank=True, null=True)),
                ('average_bandwidth', models.PositiveIntegerField(blank=True, null=True)),
                ('codecs', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hls_renditions', to='files.media')),
            ],
            options={
                'ordering': ['codec', 'resolution'],
                'indexes': [models.Index(fields=['media', 'codec', 'resolution'], name='files_media_media_i_0c9b79_idx')],
                'constraints': [models.UniqueConstraint(fields=('media', 'codec', 'resolution'), name='unique_media_hls_rendition')],
            },
        ),
    ]
