# Generated by Django 5.1.6 on 2026-05-10 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0014_media_hls_hevc_file'),
        ('ledger', '0029_depositsession_expected_onchain_raw_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatorSubscriptionPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64)),
                ('name', models.CharField(max_length=100)),
                ('price_tokens', models.BigIntegerField()),
                ('access_policy', models.CharField(choices=[('future_releases', 'Future releases'), ('active_full_catalog', 'Active full catalog'), ('selected_collections', 'Selected collections')], db_index=True, default='future_releases', max_length=32)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creator_subscription_plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CreatorSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(db_index=True, default='active', max_length=16)),
                ('current_period_start', models.DateTimeField(db_index=True)),
                ('current_period_end', models.DateTimeField(db_index=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creator_subscribers', to=settings.AUTH_USER_MODEL)),
                ('last_txn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ledger.ledgertransaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creator_subscriptions', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='premium.creatorsubscriptionplan')),
            ],
        ),
        migrations.CreateModel(
            name='MediaPurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_tokens', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='premium_purchases', to='files.media')),
                ('txn', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='premium_media_purchase', to='ledger.ledgertransaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='premium_media_purchases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PremiumCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='premium_collections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='creatorsubscriptionplan',
            name='included_collections',
            field=models.ManyToManyField(blank=True, related_name='subscription_plans', to='premium.premiumcollection'),
        ),
        migrations.CreateModel(
            name='PremiumCollectionMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_media', to='premium.premiumcollection')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='premium_collection_links', to='files.media')),
            ],
        ),
        migrations.CreateModel(
            name='PremiumMediaAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_tokens', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('disabled', 'Disabled')], db_index=True, default='draft', max_length=32)),
                ('storage_backend', models.CharField(choices=[('direct_url', 'Direct URL'), ('s3', 'S3')], default='direct_url', max_length=32)),
                ('playback_format', models.CharField(choices=[('mp4', 'MP4'), ('hls', 'HLS')], default='mp4', max_length=16)),
                ('direct_url', models.URLField(blank=True, default='')),
                ('storage_bucket', models.CharField(blank=True, default='', max_length=255)),
                ('storage_key', models.CharField(blank=True, default='', max_length=1024)),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('content_type', models.CharField(blank=True, default='video/mp4', max_length=128)),
                ('codec', models.CharField(blank=True, default='h264', max_length=32)),
                ('video_height', models.PositiveIntegerField(default=1080)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('premium_published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='premium_asset', to='files.media')),
            ],
        ),
        migrations.CreateModel(
            name='PremiumMediaUnlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('purchase', 'Purchase'), ('subscription', 'Subscription'), ('admin', 'Admin'), ('promo', 'Promo')], db_index=True, max_length=32)),
                ('unlocked_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('revoked_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='premium_unlocks', to='files.media')),
                ('source_subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='premium.creatorsubscription')),
                ('source_txn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ledger.ledgertransaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='premium_unlocks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='creatorsubscription',
            index=models.Index(fields=['user', 'creator', 'status', 'current_period_end'], name='premium_cre_user_id_91de1e_idx'),
        ),
        migrations.AddConstraint(
            model_name='mediapurchase',
            constraint=models.UniqueConstraint(fields=('user', 'media'), name='unique_media_purchase_per_user'),
        ),
        migrations.AddConstraint(
            model_name='premiumcollection',
            constraint=models.UniqueConstraint(fields=('creator', 'slug'), name='unique_premium_collection_slug_per_creator'),
        ),
        migrations.AddConstraint(
            model_name='creatorsubscriptionplan',
            constraint=models.UniqueConstraint(fields=('creator', 'code'), name='unique_creator_subscription_plan_code'),
        ),
        migrations.AddConstraint(
            model_name='premiumcollectionmedia',
            constraint=models.UniqueConstraint(fields=('collection', 'media'), name='unique_media_per_premium_collection'),
        ),
        migrations.AddIndex(
            model_name='premiummediaasset',
            index=models.Index(fields=['status', 'premium_published_at'], name='premium_pre_status_8c9cd9_idx'),
        ),
        migrations.AddIndex(
            model_name='premiummediaunlock',
            index=models.Index(fields=['user', 'revoked_at', '-unlocked_at'], name='premium_pre_user_id_bd3f50_idx'),
        ),
        migrations.AddIndex(
            model_name='premiummediaunlock',
            index=models.Index(fields=['media', 'revoked_at'], name='premium_pre_media_i_d748f8_idx'),
        ),
        migrations.AddConstraint(
            model_name='premiummediaunlock',
            constraint=models.UniqueConstraint(fields=('user', 'media'), name='unique_premium_unlock_per_user_media'),
        ),
    ]
