# Generated by Django 5.1.6 on 2026-07-11 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0017_mediahlsrendition'),
        ('ledger', '0033_tokenpack_image'),
        ('premium', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatorSubscriptionPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateTimeField(db_index=True)),
                ('period_end', models.DateTimeField(db_index=True)),
                ('price_tokens', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PremiumMediaRelease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('released_at', models.DateTimeField(db_index=True)),
                ('processed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='creatorsubscription',
            name='past_due_since',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='creatorsubscription',
            name='renewal_attempted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='creatorsubscriptionplan',
            name='billing_period_days',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddConstraint(
            model_name='creatorsubscription',
            constraint=models.UniqueConstraint(fields=('user', 'creator'), name='uniq_subscriber_creator'),
        ),
        migrations.AddConstraint(
            model_name='creatorsubscriptionplan',
            constraint=models.CheckConstraint(condition=models.Q(('price_tokens__gt', 0)), name='prem_sub_plan_price_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='creatorsubscriptionplan',
            constraint=models.CheckConstraint(condition=models.Q(('billing_period_days__gt', 0)), name='prem_sub_plan_days_gt_0'),
        ),
        migrations.AddField(
            model_name='creatorsubscriptionperiod',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creator_subscription_periods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creatorsubscriptionperiod',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paid_periods', to='premium.creatorsubscriptionplan'),
        ),
        migrations.AddField(
            model_name='creatorsubscriptionperiod',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paid_periods', to='premium.creatorsubscription'),
        ),
        migrations.AddField(
            model_name='creatorsubscriptionperiod',
            name='txn',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='creator_subscription_period', to='ledger.ledgertransaction'),
        ),
        migrations.AddField(
            model_name='premiummediarelease',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premium_media_releases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='premiummediarelease',
            name='media',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='premium_release', to='files.media'),
        ),
        migrations.AddIndex(
            model_name='creatorsubscriptionperiod',
            index=models.Index(fields=['subscription', 'period_start', 'period_end'], name='prem_sub_period_sub_idx'),
        ),
        migrations.AddIndex(
            model_name='creatorsubscriptionperiod',
            index=models.Index(fields=['creator', 'period_start', 'period_end'], name='prem_sub_period_creator_idx'),
        ),
        migrations.AddConstraint(
            model_name='creatorsubscriptionperiod',
            constraint=models.UniqueConstraint(fields=('subscription', 'period_start'), name='uniq_sub_period_start'),
        ),
        migrations.AddConstraint(
            model_name='creatorsubscriptionperiod',
            constraint=models.CheckConstraint(condition=models.Q(('period_end__gt', models.F('period_start'))), name='sub_period_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='creatorsubscriptionperiod',
            constraint=models.CheckConstraint(condition=models.Q(('price_tokens__gt', 0)), name='sub_period_price_gt_0'),
        ),
        migrations.AddIndex(
            model_name='premiummediarelease',
            index=models.Index(fields=['creator', 'released_at'], name='prem_release_creator_idx'),
        ),
        migrations.AddIndex(
            model_name='premiummediarelease',
            index=models.Index(fields=['processed_at', 'id'], name='prem_release_pending_idx'),
        ),
    ]
